[package]
name = "uecp-rs"
version = "0.1.0"
authors = ["Stéphane Lepin <stephane.lepin@gmail.com>"]
edition = "2018"

[dependencies]
bytebuffer = "0.2.1"
phf = { version = "0.8.0", features = ["macros"] }
num-traits = "0.2"
num-derive = "0.3"